name: Sync Feedback

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    # environment: Production
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install @octokit/rest dotenv
        
      - name: Sync feedback
        env:
          GITHUB_TOKEN: ${{ github.token }}  # Use default token
          GITHUB_REPO_OWNER: anupulu
          GITHUB_REPO_NAME: anupulu.github.io
        run: node .github/scripts/sync-feedback.mjs